# ==========================================
# 1. DESTINATION : SINK NATS JETSTREAM
# ==========================================
debezium.sink.type=nats-jetstream
debezium.sink.nats-jetstream.url=nats://nats:4222

debezium.sink.nats-jetstream.create-stream=false

# ==========================================
# 2. SOURCE : CONNECTOR POSTGRESQL (WAL)
# ==========================================
debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.offset.storage=org.apache.kafka.connect.storage.FileOffsetBackingStore
# Sauvegarde locale de la position de lecture (Offset) de Debezium
debezium.source.offset.storage.file.filename=data/offsets.dat
debezium.source.offset.flush.interval.ms=1000

# Informations de connexion à votre base locale
debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=lab_user
debezium.source.database.password=lab_password
debezium.source.database.dbname=lab_db

# Plugin officiel et natif de Postgres pour le CDC
debezium.source.plugin.name=pgoutput

# ==========================================
# 3. ROUTAGE & FILTRAGE (Évite la pollution)
# ==========================================
# Préfixe qui sera ajouté devant les sujets NATS (ex: events.order_schema.outbox)
debezium.source.topic.prefix=events
debezium.source.slot.name=debezium_cdc_slot
debezium.source.slot.drop.on.stop=false

# IMPORTANT : Écoute uniquement vos tables outbox applicatives
debezium.source.table.include.list=order_schema.outbox,inventory_schema.outbox

# ÉTAPE CRUCIAL : Active la transformation d'aplatissement (Unwrapping)
debezium.source.transforms=unwrap
debezium.source.transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
debezium.source.transforms.unwrap.drop.tombstones=true
