# ==========================================
# MODULE NOTIFICATION : NATS JETSTREAM -> INBOX
# ==========================================

input:
  nats_jetstream:
    urls: [ "nats://nats:4222" ]
    stream: EVENT_STORE

    # 1. L'Abonnement (Les Sujets)
    # L'Order est l'Orchestrateur, il doit écouter les réponses de l'Inventory (Participant)
    # Un seul champ 'subject' (Singulier) avec Wildcard
    # Capte events.OrderValidatedEvent ET events.OrderCancelledEvent
    subject: "events.order.*"

    # 2. La Résilience NATS
    durable: notification-consumer

pipeline:
  processors:
    - log:
        level: INFO
        message: 'Contenu brut NATS : ${! content() }'

    - mapping: |
        root.message_id = this.eventId
        root.handler_name = "Notification-" + this.eventType
        root.correlation_id = this.correlationId
        root.payload = this.payload
    - log:
        level: INFO
        message: "Contenu mappé : ${! content() }"

output:
  sql_insert:
    driver: postgres
    dsn: postgres://lab_user:lab_password@postgres:5432/lab_db
    table: notification_schema.inbox
    columns: [ message_id, handler_name, correlation_id, payload ]
    args_mapping: |
      root = [
        this.message_id,
        this.handler_name,
        this.correlation_id,
        this.payload.string()
      ]
    # 3. L'Idempotence (Le Bouclier Anti-Doublon)
    # Si le (message_id + handler_name) existe déjà en base, Postgres refuse l'insertion.
    # Le 'DO NOTHING' dit à Redpanda : "C'est pas grave, c'est un doublon, fais un ACK à NATS et passe à la suite".
    suffix: "ON CONFLICT (message_id, handler_name) DO NOTHING"